// GENERATED by scripts/gen-catalog.ts from content/challenges.ts. Do not edit by hand.
// Contains no answers or explanations: those live only in Postgres (private.quiz_answers).
import type { Challenge } from "./types";

export const challenges: Challenge[] = [
  {
    "id": "html-check",
    "skillId": "html",
    "type": "quiz",
    "title": "HTML skill check",
    "description": "Pass this to master HTML and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does HTML stand for?",
        "type": "multiple-choice",
        "options": [
          "Home Tool Markup Language",
          "High Tech Modern Language",
          "Hyper Text Markup Language",
          "Hyperlinks and Text Markup Language"
        ],
        "hint": "Links between text (Hyper), the content (Text), and how it's structured (Markup)."
      },
      {
        "question": "Which tag is used for the largest heading?",
        "type": "multiple-choice",
        "options": [
          "<head>",
          "<heading>",
          "<h1>",
          "<h6>"
        ]
      },
      {
        "question": "HTML tags are case-sensitive.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "The _____ tag defines an unordered list.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "html-1",
    "skillId": "html",
    "type": "code",
    "lang": "html",
    "title": "Your first page",
    "description": "Build a page with a title, a heading and a paragraph.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "<!DOCTYPE html>\n<html>\n  <!-- add a head with a title, and a body -->\n</html>\n",
    "hints": [
      "Put a <title> inside <head>",
      "Use <h1> for the heading and <p> for the paragraph",
      "Both go inside <body>"
    ],
    "tests": [
      {
        "lang": "html",
        "selector": "head > title",
        "label": "has a <title> in <head>"
      },
      {
        "lang": "html",
        "selector": "body h1",
        "label": "has an <h1> in <body>"
      },
      {
        "lang": "html",
        "selector": "body p",
        "label": "has a <p> in <body>"
      }
    ]
  },
  {
    "id": "css-check",
    "skillId": "css",
    "type": "quiz",
    "title": "CSS skill check",
    "description": "Pass this to master CSS and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which declaration makes an element a flex container?",
        "type": "multiple-choice",
        "options": [
          "flex: 1",
          "display: flex",
          "position: flex",
          "align: flex"
        ]
      },
      {
        "question": "Padding sits outside an element's border.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "The unit relative to the root element's font size is ___.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "css-1",
    "skillId": "css",
    "type": "code",
    "lang": "css",
    "title": "Center a div",
    "description": "Center .container's children horizontally and vertically with flexbox.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": ".container {\n  /* your CSS here */\n}\n",
    "hints": [
      "Start with display: flex",
      "justify-content handles the main axis",
      "align-items handles the cross axis"
    ],
    "tests": [
      {
        "lang": "css",
        "selector": ".container",
        "prop": "display",
        "value": [
          "flex",
          "inline-flex"
        ],
        "label": "display: flex"
      },
      {
        "lang": "css",
        "selector": ".container",
        "prop": "justify-content",
        "value": [
          "center"
        ],
        "label": "justify-content: center"
      },
      {
        "lang": "css",
        "selector": ".container",
        "prop": "align-items",
        "value": [
          "center"
        ],
        "label": "align-items: center"
      }
    ]
  },
  {
    "id": "css-2",
    "skillId": "css",
    "type": "code",
    "lang": "css",
    "title": "Three-column grid",
    "description": "Make .grid a grid with three equal columns and a gap between them.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": ".grid {\n  \n}\n",
    "hints": [
      "display: grid",
      "repeat(3, 1fr) makes three equal columns",
      "gap sets spacing between cells, and 0 doesn't count"
    ],
    "tests": [
      {
        "lang": "css",
        "selector": ".grid",
        "prop": "display",
        "value": [
          "grid",
          "inline-grid"
        ],
        "label": "display: grid"
      },
      {
        "lang": "css",
        "selector": ".grid",
        "prop": "grid-template-columns",
        "value": [
          "repeat(3, 1fr)",
          "1fr 1fr 1fr",
          "repeat(3, minmax(0, 1fr))",
          "minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1fr)"
        ],
        "label": "three equal columns"
      },
      {
        "lang": "css",
        "selector": ".grid",
        "prop": [
          "row-gap",
          "column-gap"
        ],
        "value": "non-zero",
        "label": "a gap bigger than 0"
      }
    ]
  },
  {
    "id": "javascript-check",
    "skillId": "javascript",
    "type": "quiz",
    "title": "JavaScript skill check",
    "description": "Pass this to master JavaScript and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does [1, 2, 3].map(x => x * 2) return?",
        "type": "multiple-choice",
        "options": [
          "[1, 2, 3]",
          "[2, 4, 6]",
          "6",
          "undefined"
        ]
      },
      {
        "question": "`const` makes an object immutable.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which operator compares value AND type?",
        "type": "multiple-choice",
        "options": [
          "!=",
          "===",
          "=",
          "=="
        ]
      }
    ]
  },
  {
    "id": "js-1",
    "skillId": "javascript",
    "type": "code",
    "lang": "js",
    "title": "Write a function",
    "description": "Write add(a, b) that returns the sum of two numbers.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function add(a, b) {\n  // your code here\n}\n",
    "hints": [
      "Use the return keyword",
      "Return a + b"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "add(2, 3)",
        "expected": 5
      },
      {
        "lang": "js",
        "expr": "add(10, 20)",
        "expected": 30
      },
      {
        "lang": "js",
        "expr": "add(-1, 1)",
        "expected": 0
      }
    ]
  },
  {
    "id": "js-2",
    "skillId": "javascript",
    "type": "code",
    "lang": "js",
    "title": "Reverse a string",
    "description": "Write reverse(str) that returns the string backwards.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function reverse(str) {\n  \n}\n",
    "hints": [
      "Strings can be split into arrays",
      "Arrays have a reverse() method",
      "join('') turns an array back into a string"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "reverse('abc')",
        "expected": "cba"
      },
      {
        "lang": "js",
        "expr": "reverse('')",
        "expected": ""
      },
      {
        "lang": "js",
        "expr": "reverse('racecar')",
        "expected": "racecar"
      }
    ]
  },
  {
    "id": "js-3",
    "skillId": "javascript",
    "type": "code",
    "lang": "js",
    "title": "FizzBuzz",
    "description": "Write fizzBuzz(n) returning an array for 1..n: 'Fizz' for multiples of 3, 'Buzz' for 5, 'FizzBuzz' for both, otherwise the number.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "function fizzBuzz(n) {\n  const out = [];\n  \n  return out;\n}\n",
    "hints": [
      "Loop from 1 to n inclusive",
      "Check the 'both' case (i % 15) first",
      "Push numbers as numbers, not strings"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "fizzBuzz(5)",
        "expected": [
          1,
          2,
          "Fizz",
          4,
          "Buzz"
        ]
      },
      {
        "lang": "js",
        "expr": "fizzBuzz(15)[14]",
        "expected": "FizzBuzz"
      },
      {
        "lang": "js",
        "expr": "fizzBuzz(0)",
        "expected": []
      }
    ]
  },
  {
    "id": "js-game-1",
    "skillId": "javascript",
    "type": "game",
    "gameType": "debugger",
    "title": "Planet Debugger",
    "description": "Five planets, five classic JavaScript bugs. Fix each snippet so it prints the right output.",
    "difficulty": "intermediate",
    "xpReward": 100
  },
  {
    "id": "a11y-check",
    "skillId": "a11y",
    "type": "quiz",
    "title": "Accessibility skill check",
    "description": "Pass this to master Accessibility and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What should a purely decorative image's alt text be?",
        "type": "multiple-choice",
        "options": [
          "An empty string (alt=\"\")",
          "The file name",
          "\"image\"",
          "Leave out the alt attribute"
        ]
      },
      {
        "question": "A <div> with an onClick handler is as accessible as a <button>.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Minimum WCAG AA contrast for normal body text?",
        "type": "multiple-choice",
        "options": [
          "2:1",
          "4.5:1",
          "3:1",
          "7:1"
        ]
      }
    ]
  },
  {
    "id": "a11y-1",
    "skillId": "a11y",
    "type": "code",
    "lang": "html",
    "title": "Accessible sign-up form",
    "description": "Fix this form for screen reader and keyboard users: describe the logo in alt text, give every input a label, and replace the clickable div with a real submit button.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "<form>\n  <img src=\"logo.png\">\n  <input type=\"email\">\n  <div onclick=\"submit()\">Sign up</div>\n</form>\n",
    "hints": [
      "The logo carries meaning, so describe it: alt=\"SkillVerse\"",
      "Label the input with <label for=\"email\">Email</label> plus id=\"email\", or wrap the input inside the <label>",
      "A <button> inside a form submits it by default, and it works with the keyboard for free",
      "Delete the div once the button replaces it"
    ],
    "tests": [
      {
        "lang": "html",
        "check": "img-alt",
        "label": "the logo has alt text"
      },
      {
        "lang": "html",
        "check": "labelled-controls",
        "label": "every input has a label"
      },
      {
        "lang": "html",
        "check": "submit-button",
        "label": "the form has a submit button with text"
      },
      {
        "lang": "html",
        "check": "no-click-handlers",
        "label": "no clickable div left over"
      }
    ]
  },
  {
    "id": "tailwind-check",
    "skillId": "tailwind",
    "type": "quiz",
    "title": "Tailwind skill check",
    "description": "Pass this to master Tailwind and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which class applies only from the md breakpoint up?",
        "type": "multiple-choice",
        "options": [
          "md:flex",
          "flex:md",
          "@md flex",
          "flex-md"
        ]
      },
      {
        "question": "Tailwind ships every utility class to production whether you use it or not.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "The utility for display: grid is ___.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "typescript-check",
    "skillId": "typescript",
    "type": "quiz",
    "title": "TypeScript skill check",
    "description": "Pass this to master TypeScript and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What is the inferred type of x in let x = [1, 'a']?",
        "type": "multiple-choice",
        "options": [
          "unknown",
          "[number, string]",
          "any[]",
          "(string | number)[]"
        ]
      },
      {
        "question": "TypeScript types exist at runtime.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which check narrows value: string | number to string?",
        "type": "multiple-choice",
        "options": [
          "value!",
          "value instanceof String",
          "typeof value === 'string'",
          "value as string"
        ]
      }
    ]
  },
  {
    "id": "typescript-1",
    "skillId": "typescript",
    "type": "code",
    "lang": "js",
    "title": "Guard against bad data",
    "description": "Types vanish at runtime, so JSON from an API needs a real check. Write isUser(value), the body of a `value is User` type guard: true only for objects with a string name and a number age.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "// type User = { name: string; age: number }\n// In TypeScript: function isUser(value: unknown): value is User\n// The editor runs plain JavaScript, so leave out the type annotations.\nfunction isUser(value) {\n  \n}\n",
    "hints": [
      "typeof value === 'object' is true for null too, so rule null out",
      "Then check typeof value.name and typeof value.age"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "isUser({ name: 'Ada', age: 36 })",
        "expected": true
      },
      {
        "lang": "js",
        "expr": "isUser({ name: 'Ada' })",
        "expected": false
      },
      {
        "lang": "js",
        "expr": "isUser({ name: 'Ada', age: '36' })",
        "expected": false
      },
      {
        "lang": "js",
        "expr": "isUser(null)",
        "expected": false
      }
    ]
  },
  {
    "id": "react-check",
    "skillId": "react",
    "type": "quiz",
    "title": "React skill check",
    "description": "Pass this to master React and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which hook runs side effects after render?",
        "type": "multiple-choice",
        "options": [
          "useState",
          "useMemo",
          "useRef",
          "useEffect"
        ]
      },
      {
        "question": "To add an item, call items.push(x) and then setItems(items).",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Items rendered with .map() need a unique ___ prop.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "react-1",
    "skillId": "react",
    "type": "code",
    "lang": "js",
    "title": "A reducer for a to-do list",
    "description": "Write todosReducer(todos, action) for useReducer. Handle 'added' ({ id, text }, new items start with done: false), 'toggled' ({ id }) and 'deleted' ({ id }). Return new arrays and objects instead of changing the old ones, and return todos unchanged for any other action.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "// todos: [{ id, text, done }]\nfunction todosReducer(todos, action) {\n  switch (action.type) {\n    // handle 'added', 'toggled' and 'deleted' here\n    default:\n      return todos;\n  }\n}\n",
    "hints": [
      "Adding: return [...todos, newTodo] instead of calling push",
      "Toggling: map over todos and copy the one that matches with { ...t, done: !t.done }",
      "Deleting: filter keeps every todo whose id doesn't match"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "todosReducer([], { type: 'added', id: 1, text: 'Learn React' })",
        "expected": [
          {
            "id": 1,
            "text": "Learn React",
            "done": false
          }
        ]
      },
      {
        "lang": "js",
        "expr": "todosReducer([{ id: 1, text: 'a', done: false }, { id: 2, text: 'b', done: false }], { type: 'toggled', id: 2 })",
        "expected": [
          {
            "id": 1,
            "text": "a",
            "done": false
          },
          {
            "id": 2,
            "text": "b",
            "done": true
          }
        ]
      },
      {
        "lang": "js",
        "expr": "todosReducer([{ id: 1, text: 'a', done: false }, { id: 2, text: 'b', done: true }], { type: 'deleted', id: 1 })",
        "expected": [
          {
            "id": 2,
            "text": "b",
            "done": true
          }
        ]
      },
      {
        "lang": "js",
        "expr": "(() => { const todos = [{ id: 1, text: 'a', done: false }]; todosReducer(todos, { type: 'toggled', id: 1 }); todosReducer(todos, { type: 'added', id: 2, text: 'b' }); return todos; })()",
        "expected": [
          {
            "id": 1,
            "text": "a",
            "done": false
          }
        ],
        "label": "leaves the old todos untouched after toggling and adding"
      },
      {
        "lang": "js",
        "expr": "(() => { const todos = []; return todosReducer(todos, { type: 'renamed' }) === todos; })()",
        "expected": true,
        "label": "returns the same array for an unknown action"
      }
    ]
  },
  {
    "id": "nextjs-check",
    "skillId": "nextjs",
    "type": "quiz",
    "title": "Next.js skill check",
    "description": "Pass this to master Next.js and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "In the App Router, which file defines a route's UI?",
        "type": "multiple-choice",
        "options": [
          "index.tsx",
          "page.tsx",
          "route.tsx",
          "view.tsx"
        ]
      },
      {
        "question": "App Router components are Server Components by default.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which directive marks a client component?",
        "type": "multiple-choice",
        "options": [
          "\"use browser\"",
          "\"client only\"",
          "export const client = true",
          "\"use client\""
        ]
      }
    ]
  },
  {
    "id": "nodejs-check",
    "skillId": "nodejs",
    "type": "quiz",
    "title": "Node.js skill check",
    "description": "Pass this to master Node.js and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which file lists a Node project's dependencies?",
        "type": "multiple-choice",
        "options": [
          "node.config.js",
          "npmfile",
          "deps.txt",
          "package.json"
        ]
      },
      {
        "question": "Node runs your JavaScript on many threads by default.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "You can only use await inside a function marked ___ (or at the top level of an ES module).",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "nodejs-1",
    "skillId": "nodejs",
    "type": "code",
    "lang": "js",
    "title": "Parse a query string",
    "description": "Write parseQuery(qs) turning 'a=1&b=two' into { a: '1', b: 'two' }. Decode percent-escapes like %20, and return {} for an empty string.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function parseQuery(qs) {\n  \n}\n",
    "hints": [
      "URLSearchParams is built in",
      "Object.fromEntries turns entries into an object"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "parseQuery('a=1&b=two')",
        "expected": {
          "a": "1",
          "b": "two"
        }
      },
      {
        "lang": "js",
        "expr": "parseQuery('')",
        "expected": {}
      },
      {
        "lang": "js",
        "expr": "parseQuery('q=hello%20world')",
        "expected": {
          "q": "hello world"
        }
      }
    ]
  },
  {
    "id": "express-check",
    "skillId": "express",
    "type": "quiz",
    "title": "Express skill check",
    "description": "Pass this to master Express and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does calling next() in middleware do?",
        "type": "multiple-choice",
        "options": [
          "Restarts the server",
          "Ends the response",
          "Skips every remaining route",
          "Passes control to the next middleware"
        ]
      },
      {
        "question": "Express error-handling middleware takes four arguments: (err, req, res, next).",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "With route '/users/:id', how do you read 42 from GET /users/42?",
        "type": "multiple-choice",
        "options": [
          "req.body.id",
          "req.query.id",
          "req.id",
          "req.params.id"
        ]
      }
    ]
  },
  {
    "id": "express-1",
    "skillId": "express",
    "type": "code",
    "lang": "js",
    "title": "Match a route",
    "description": "Write matchRoute(pattern, path): return an object of params if it matches, otherwise null. matchRoute('/users/:id', '/users/42') → { id: '42' }.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "function matchRoute(pattern, path) {\n  \n}\n",
    "hints": [
      "Split both on '/'",
      "Different segment counts means no match",
      "Segments starting with ':' capture a param"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "matchRoute('/users/:id', '/users/42')",
        "expected": {
          "id": "42"
        }
      },
      {
        "lang": "js",
        "expr": "matchRoute('/users/:id/posts/:postId', '/users/7/posts/9')",
        "expected": {
          "id": "7",
          "postId": "9"
        }
      },
      {
        "lang": "js",
        "expr": "matchRoute('/users/:id', '/teams/42')",
        "expected": null
      },
      {
        "lang": "js",
        "expr": "matchRoute('/users/:id', '/users/42/extra')",
        "expected": null
      }
    ]
  },
  {
    "id": "rest-apis-check",
    "skillId": "rest-apis",
    "type": "quiz",
    "title": "REST APIs skill check",
    "description": "Pass this to master REST APIs and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Status code for a newly created resource?",
        "type": "multiple-choice",
        "options": [
          "200 OK",
          "302 Found",
          "201 Created",
          "204 No Content"
        ]
      },
      {
        "question": "GET requests should never change server state.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which verb replaces a resource entirely?",
        "type": "multiple-choice",
        "options": [
          "GET",
          "PATCH",
          "POST",
          "PUT"
        ]
      }
    ]
  },
  {
    "id": "rest-apis-1",
    "skillId": "rest-apis",
    "type": "code",
    "lang": "js",
    "title": "Paginate a collection",
    "description": "Write paginate(items, page, perPage) for a GET /items?page=2 endpoint. page starts at 1. Return { data, page, totalPages, nextPage }, where nextPage is null on the last page or past the end.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function paginate(items, page, perPage) {\n  \n}\n",
    "hints": [
      "Page 1 starts at index 0, so the start index is (page - 1) * perPage",
      "totalPages is Math.ceil(items.length / perPage)",
      "slice never throws on a range past the end, it just returns []"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "paginate([1, 2, 3, 4, 5], 1, 2)",
        "expected": {
          "data": [
            1,
            2
          ],
          "page": 1,
          "totalPages": 3,
          "nextPage": 2
        }
      },
      {
        "lang": "js",
        "expr": "paginate([1, 2, 3, 4, 5], 3, 2)",
        "expected": {
          "data": [
            5
          ],
          "page": 3,
          "totalPages": 3,
          "nextPage": null
        }
      },
      {
        "lang": "js",
        "expr": "paginate([1, 2, 3], 5, 2)",
        "expected": {
          "data": [],
          "page": 5,
          "totalPages": 2,
          "nextPage": null
        }
      },
      {
        "lang": "js",
        "expr": "paginate([], 1, 10)",
        "expected": {
          "data": [],
          "page": 1,
          "totalPages": 0,
          "nextPage": null
        }
      }
    ]
  },
  {
    "id": "sql-check",
    "skillId": "sql",
    "type": "quiz",
    "title": "SQL skill check",
    "description": "Pass this to master SQL and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which clause filters groups after aggregation?",
        "type": "multiple-choice",
        "options": [
          "WHERE",
          "HAVING",
          "ORDER BY",
          "GROUP BY"
        ]
      },
      {
        "question": "An INNER JOIN keeps rows that have no match in the other table.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Remove duplicate rows with SELECT ___ …",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "postgres-check",
    "skillId": "postgres",
    "type": "quiz",
    "title": "PostgreSQL skill check",
    "description": "Pass this to master PostgreSQL and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which type stores JSON in a binary, indexable form?",
        "type": "multiple-choice",
        "options": [
          "hstore",
          "text",
          "json",
          "jsonb"
        ]
      },
      {
        "question": "A transaction applies all of its statements or none of them.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "What does Row Level Security control?",
        "type": "multiple-choice",
        "options": [
          "Which rows each user can read or write",
          "Which columns are indexed",
          "Disk encryption",
          "Replication lag"
        ]
      }
    ]
  },
  {
    "id": "auth-check",
    "skillId": "auth",
    "type": "quiz",
    "title": "Auth skill check",
    "description": "Pass this to master Auth and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "How should passwords be stored?",
        "type": "multiple-choice",
        "options": [
          "Hashed with a slow algorithm like bcrypt or argon2",
          "Encrypted with AES",
          "Plain text, since HTTPS protects them",
          "Base64-encoded"
        ]
      },
      {
        "question": "Anyone holding a (non-encrypted) JWT can read its payload.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "OAuth 2.0 is mainly a protocol for…",
        "type": "multiple-choice",
        "options": [
          "Encrypting databases",
          "Load balancing",
          "Password hashing",
          "Delegated authorization"
        ]
      }
    ]
  },
  {
    "id": "auth-1",
    "skillId": "auth",
    "type": "code",
    "lang": "js",
    "title": "Check token expiry",
    "description": "Write isExpired(payload, nowMs). JWT `exp` is in seconds; nowMs is milliseconds. Expired when now ≥ exp.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function isExpired(payload, nowMs) {\n  \n}\n",
    "hints": [
      "Convert exp to milliseconds (× 1000)",
      "Use >= so a token is expired exactly at exp"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "isExpired({ exp: 100 }, 100000)",
        "expected": true
      },
      {
        "lang": "js",
        "expr": "isExpired({ exp: 200 }, 100000)",
        "expected": false
      },
      {
        "lang": "js",
        "expr": "isExpired({ exp: 100 }, 99999)",
        "expected": false
      }
    ]
  },
  {
    "id": "fastapi-check",
    "skillId": "fastapi",
    "type": "quiz",
    "title": "FastAPI skill check",
    "description": "Pass this to master FastAPI and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does FastAPI use to validate request bodies?",
        "type": "multiple-choice",
        "options": [
          "Pydantic models",
          "SQLAlchemy",
          "Regular expressions",
          "Hand-written if statements"
        ]
      },
      {
        "question": "FastAPI serves interactive OpenAPI docs at /docs automatically.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Declare an async endpoint with `___ def read_item(...)`.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "python-check",
    "skillId": "python",
    "type": "quiz",
    "title": "Python skill check",
    "description": "Pass this to master Python and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What is len([1, [2, 3], 4])?",
        "type": "multiple-choice",
        "options": [
          "Error",
          "4",
          "3",
          "2"
        ]
      },
      {
        "question": "Python lists are immutable.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which of these creates a dict?",
        "type": "multiple-choice",
        "options": [
          "{'a', 1}",
          "['a', 1]",
          "{'a': 1}",
          "('a', 1)"
        ]
      }
    ]
  },
  {
    "id": "pandas-check",
    "skillId": "pandas",
    "type": "quiz",
    "title": "pandas skill check",
    "description": "Pass this to master pandas and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Select rows where the age column is over 30:",
        "type": "multiple-choice",
        "options": [
          "df.where(age > 30)",
          "df.select('age > 30')",
          "df[df['age'] > 30]",
          "df.filter(age > 30)"
        ]
      },
      {
        "question": "df.dropna() modifies df in place by default.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Mean salary per department?",
        "type": "multiple-choice",
        "options": [
          "df.mean('dept')",
          "df.groupby('dept')['salary'].mean()",
          "df.pivot('salary')",
          "df.agg('dept')"
        ]
      }
    ]
  },
  {
    "id": "pandas-1",
    "skillId": "pandas",
    "type": "code",
    "lang": "js",
    "title": "Group by, by hand",
    "description": "Write groupMean(rows, key, field) returning { [group]: mean } — what df.groupby(key)[field].mean() does.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "function groupMean(rows, key, field) {\n  \n}\n",
    "hints": [
      "Accumulate a sum and count per group",
      "Then divide sum by count for each group"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "groupMean([{d:'a',s:10},{d:'a',s:20},{d:'b',s:5}], 'd', 's')",
        "expected": {
          "a": 15,
          "b": 5
        }
      },
      {
        "lang": "js",
        "expr": "groupMean([], 'd', 's')",
        "expected": {}
      },
      {
        "lang": "js",
        "expr": "groupMean([{d:'x',s:1},{d:'y',s:2},{d:'x',s:4}], 'd', 's')",
        "expected": {
          "x": 2.5,
          "y": 2
        }
      }
    ]
  },
  {
    "id": "data-viz-check",
    "skillId": "data-viz",
    "type": "quiz",
    "title": "Data Viz skill check",
    "description": "Pass this to master Data Viz and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Best chart for a trend over time?",
        "type": "multiple-choice",
        "options": [
          "Treemap",
          "Scatter plot",
          "Line chart",
          "Pie chart"
        ]
      },
      {
        "question": "Bar charts should start their value axis at zero.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Comparing 12 categories' share of a whole is clearest as…",
        "type": "multiple-choice",
        "options": [
          "A line chart",
          "A sorted bar chart",
          "A 3D pie chart",
          "A 12-slice pie chart"
        ]
      }
    ]
  },
  {
    "id": "data-viz-1",
    "skillId": "data-viz",
    "type": "code",
    "lang": "js",
    "title": "Bin values for a histogram",
    "description": "Write histogram(values, min, max, bins): split [min, max] into equal-width bins and count the values in each. A value equal to max goes in the last bin, and values outside the range are ignored.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "function histogram(values, min, max, bins) {\n  const counts = new Array(bins).fill(0);\n  \n  return counts;\n}\n",
    "hints": [
      "Each bin is (max - min) / bins wide",
      "Math.floor((v - min) / width) gives the bin index",
      "v === max gives index bins, one past the end, so clamp it"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "histogram([1, 2, 2, 3, 9], 0, 10, 5)",
        "expected": [
          1,
          3,
          0,
          0,
          1
        ]
      },
      {
        "lang": "js",
        "expr": "histogram([0, 10], 0, 10, 2)",
        "expected": [
          1,
          1
        ]
      },
      {
        "lang": "js",
        "expr": "histogram([-1, 5, 11], 0, 10, 2)",
        "expected": [
          0,
          1
        ]
      },
      {
        "lang": "js",
        "expr": "histogram([], 0, 1, 3)",
        "expected": [
          0,
          0,
          0
        ]
      }
    ]
  },
  {
    "id": "ml-basics-check",
    "skillId": "ml-basics",
    "type": "quiz",
    "title": "ML Basics skill check",
    "description": "Pass this to master ML Basics and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "99% accuracy on training data, 60% on test data. This is…",
        "type": "multiple-choice",
        "options": [
          "Good generalisation",
          "Overfitting",
          "Regularization",
          "Underfitting"
        ]
      },
      {
        "question": "It's fine to evaluate a model on the data it was trained on.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Predicting a house price is…",
        "type": "multiple-choice",
        "options": [
          "Clustering",
          "Classification",
          "Reinforcement learning",
          "Regression"
        ]
      }
    ]
  },
  {
    "id": "ml-basics-1",
    "skillId": "ml-basics",
    "type": "code",
    "lang": "js",
    "title": "Mean squared error",
    "description": "Write mse(actual, predicted), the average of the squared differences, the usual loss for regression. Throw an Error if the arrays have different lengths.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function mse(actual, predicted) {\n  \n}\n",
    "hints": [
      "Square each difference: (actual[i] - predicted[i]) ** 2",
      "Sum them, then divide by the number of values",
      "throw new Error('...') stops early when the lengths differ"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "mse([1, 2, 3], [1, 2, 3])",
        "expected": 0
      },
      {
        "lang": "js",
        "expr": "mse([2, 4], [1, 7])",
        "expected": 5
      },
      {
        "lang": "js",
        "expr": "+mse([1, 2, 3], [2, 2, 4]).toFixed(4)",
        "expected": 0.6667
      },
      {
        "lang": "js",
        "expr": "(() => { try { mse([1, 2], [1]); return 'no error'; } catch { return 'threw'; } })()",
        "expected": "threw",
        "label": "throws when the lengths differ"
      }
    ]
  },
  {
    "id": "deep-learning-check",
    "skillId": "deep-learning",
    "type": "quiz",
    "title": "Deep Learning skill check",
    "description": "Pass this to master Deep Learning and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does gradient descent minimize?",
        "type": "multiple-choice",
        "options": [
          "The dataset size",
          "The loss function",
          "The learning rate",
          "The number of layers"
        ]
      },
      {
        "question": "Transformers rely on attention rather than recurrence.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Dense vector representations of words or items are called ___.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "deep-learning-1",
    "skillId": "deep-learning",
    "type": "code",
    "lang": "js",
    "title": "Softmax",
    "description": "Write softmax(logits), turning a model's raw scores into probabilities that sum to 1. It must stay accurate for large scores like 1000, where Math.exp overflows to Infinity.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "function softmax(logits) {\n  \n}\n",
    "hints": [
      "softmax(x)[i] = Math.exp(x[i]) / the sum of Math.exp over every x",
      "Subtracting the same number from every logit doesn't change the result",
      "So subtract Math.max(...logits) first, and the biggest exponent becomes Math.exp(0) = 1"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "softmax([0, 0]).map((p) => +p.toFixed(4))",
        "expected": [
          0.5,
          0.5
        ]
      },
      {
        "lang": "js",
        "expr": "softmax([1, 2, 3]).map((p) => +p.toFixed(4))",
        "expected": [
          0.09,
          0.2447,
          0.6652
        ]
      },
      {
        "lang": "js",
        "expr": "softmax([1000, 1000]).map((p) => +p.toFixed(4))",
        "expected": [
          0.5,
          0.5
        ]
      },
      {
        "lang": "js",
        "expr": "softmax([5])",
        "expected": [
          1
        ]
      }
    ]
  },
  {
    "id": "llm-apps-check",
    "skillId": "llm-apps",
    "type": "quiz",
    "title": "LLM Apps skill check",
    "description": "Pass this to master LLM Apps and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "RAG stands for…",
        "type": "multiple-choice",
        "options": [
          "Recursive Answer Graph",
          "Rapid API Gateway",
          "Random Attention Gradient",
          "Retrieval-Augmented Generation"
        ]
      },
      {
        "question": "Lowering temperature makes output more deterministic.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Best way to know if a prompt change made your app better?",
        "type": "multiple-choice",
        "options": [
          "Ask the model if it improved",
          "Run it against an eval set",
          "Make the prompt longer",
          "Try one example by hand"
        ]
      }
    ]
  },
  {
    "id": "llm-apps-1",
    "skillId": "llm-apps",
    "type": "code",
    "lang": "js",
    "title": "Chunk text for retrieval",
    "description": "RAG pipelines split documents into overlapping chunks before embedding them. Write chunk(text, size, overlap): each chunk is at most size characters and starts size - overlap after the previous one. Stop once a chunk reaches the end of the text. Assume 0 ≤ overlap < size.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "function chunk(text, size, overlap) {\n  const chunks = [];\n  \n  return chunks;\n}\n",
    "hints": [
      "Move the start forward by size - overlap each time",
      "text.slice(start, start + size) is safe past the end of the string",
      "Break out of the loop when start + size reaches text.length, or you'll add a chunk that's already covered"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "chunk('abcdefghij', 4, 1)",
        "expected": [
          "abcd",
          "defg",
          "ghij"
        ]
      },
      {
        "lang": "js",
        "expr": "chunk('abcdef', 2, 0)",
        "expected": [
          "ab",
          "cd",
          "ef"
        ]
      },
      {
        "lang": "js",
        "expr": "chunk('abc', 10, 2)",
        "expected": [
          "abc"
        ]
      },
      {
        "lang": "js",
        "expr": "chunk('', 4, 1)",
        "expected": []
      }
    ]
  },
  {
    "id": "git-check",
    "skillId": "git",
    "type": "quiz",
    "title": "Git skill check",
    "description": "Pass this to master Git and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which command creates and switches to a new branch?",
        "type": "multiple-choice",
        "options": [
          "git commit -b feature",
          "git switch -c feature",
          "git branch --go feature",
          "git new feature"
        ]
      },
      {
        "question": "git pull is git fetch followed by a merge (or rebase).",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Stage everything in the current directory with `git ___ .`",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "linux-check",
    "skillId": "linux",
    "type": "quiz",
    "title": "Linux skill check",
    "description": "Pass this to master Linux and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does chmod 755 give the file's owner?",
        "type": "multiple-choice",
        "options": [
          "Read, write and execute",
          "Nothing",
          "Execute only",
          "Read only"
        ]
      },
      {
        "question": "In `ls | grep log`, ls's output becomes grep's input.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Print the current working directory with ___.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "linux-1",
    "skillId": "linux",
    "type": "code",
    "lang": "js",
    "title": "Read a permission mode",
    "description": "Write toSymbolic(mode), turning an octal mode like '755' into the string ls -l shows: 'rwxr-xr-x'. The digits are owner, group and others, and each is a sum of 4 (read), 2 (write) and 1 (execute).",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function toSymbolic(mode) {\n  \n}\n",
    "hints": [
      "Handle one digit at a time: [...mode] splits the string",
      "digit & 4 is non-zero when the read bit is set. Same for & 2 and & 1"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "toSymbolic('755')",
        "expected": "rwxr-xr-x"
      },
      {
        "lang": "js",
        "expr": "toSymbolic('644')",
        "expected": "rw-r--r--"
      },
      {
        "lang": "js",
        "expr": "toSymbolic('600')",
        "expected": "rw-------"
      },
      {
        "lang": "js",
        "expr": "toSymbolic('000')",
        "expected": "---------"
      }
    ]
  },
  {
    "id": "docker-check",
    "skillId": "docker",
    "type": "quiz",
    "title": "Docker skill check",
    "description": "Pass this to master Docker and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "An image is to a container as…",
        "type": "multiple-choice",
        "options": [
          "A branch is to a commit",
          "A port is to a host",
          "A VM is to a disk",
          "A class is to an instance"
        ]
      },
      {
        "question": "Files written inside a container survive `docker rm` by default.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Why use multi-stage builds?",
        "type": "multiple-choice",
        "options": [
          "Smaller final images without build tools",
          "To run several OSes",
          "Faster network",
          "To avoid writing a Dockerfile"
        ]
      }
    ]
  },
  {
    "id": "ci-cd-check",
    "skillId": "ci-cd",
    "type": "quiz",
    "title": "CI/CD skill check",
    "description": "Pass this to master CI/CD and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Where do GitHub Actions workflows live?",
        "type": "multiple-choice",
        "options": [
          "actions/",
          ".github/workflows/",
          ".git/hooks/",
          ".ci/"
        ]
      },
      {
        "question": "CI means merging small changes often, verified by automated tests.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "A deploy breaks production. Usually the fastest safe move is…",
        "type": "multiple-choice",
        "options": [
          "Debug live in production",
          "Roll back to the last good release",
          "Turn off monitoring",
          "Delete the logs"
        ]
      }
    ]
  },
  {
    "id": "ci-cd-1",
    "skillId": "ci-cd",
    "type": "code",
    "lang": "js",
    "title": "Bump a version",
    "description": "Release pipelines bump the version before tagging. Write bump(version, part) for semantic versions: part is 'major', 'minor' or 'patch', and every number after the bumped one resets to 0.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function bump(version, part) {\n  \n}\n",
    "hints": [
      "version.split('.').map(Number) gives three numbers",
      "Strings concatenate: '9' + 1 is '91', not 10",
      "Bumping minor resets patch. Bumping major resets both"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "bump('1.4.2', 'patch')",
        "expected": "1.4.3"
      },
      {
        "lang": "js",
        "expr": "bump('1.4.2', 'minor')",
        "expected": "1.5.0"
      },
      {
        "lang": "js",
        "expr": "bump('1.4.2', 'major')",
        "expected": "2.0.0"
      },
      {
        "lang": "js",
        "expr": "bump('0.9.9', 'minor')",
        "expected": "0.10.0"
      }
    ]
  },
  {
    "id": "kubernetes-check",
    "skillId": "kubernetes",
    "type": "quiz",
    "title": "Kubernetes skill check",
    "description": "Pass this to master Kubernetes and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "The smallest deployable unit in Kubernetes is a…",
        "type": "multiple-choice",
        "options": [
          "Namespace",
          "Node",
          "Container image",
          "Pod"
        ]
      },
      {
        "question": "A Deployment keeps the desired number of replicas running.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "What gives a set of pods a stable network address?",
        "type": "multiple-choice",
        "options": [
          "A Secret",
          "A Service",
          "A ConfigMap",
          "A Volume"
        ]
      }
    ]
  },
  {
    "id": "cloud-check",
    "skillId": "cloud",
    "type": "quiz",
    "title": "Cloud skill check",
    "description": "Pass this to master Cloud and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "The rule for granting IAM permissions is…",
        "type": "multiple-choice",
        "options": [
          "Share the root credentials",
          "Least privilege",
          "Grant everything, revoke later",
          "Admin for everyone"
        ]
      },
      {
        "question": "Object storage like S3 is a good fit for user-uploaded images.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Autoscaling adds capacity based on…",
        "type": "multiple-choice",
        "options": [
          "Number of git commits",
          "The time zone",
          "Load metrics like CPU or request rate",
          "Team size"
        ]
      }
    ]
  },
  {
    "id": "cloud-1",
    "skillId": "cloud",
    "type": "code",
    "lang": "js",
    "title": "Evaluate an access policy",
    "description": "Write isAllowed(policy, action, resource) the way cloud IAM does: a request is denied unless a statement allows it, and any matching Deny wins over every Allow. A pattern ending in * matches anything that starts with the rest of it.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "// policy: [{ effect: 'Allow' | 'Deny', actions: ['s3:GetObject'], resources: ['photos/*'] }]\nfunction isAllowed(policy, action, resource) {\n  \n}\n",
    "hints": [
      "Write matches(pattern, value) first: 'photos/*' matches anything starting with 'photos/'",
      "A statement applies when one of its actions and one of its resources match",
      "Allowed = some applying statement is an Allow, and none is a Deny"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "isAllowed([{ effect: 'Allow', actions: ['s3:GetObject'], resources: ['photos/*'] }], 's3:GetObject', 'photos/cat.png')",
        "expected": true
      },
      {
        "lang": "js",
        "expr": "isAllowed([{ effect: 'Allow', actions: ['s3:GetObject'], resources: ['photos/*'] }], 's3:DeleteObject', 'photos/cat.png')",
        "expected": false
      },
      {
        "lang": "js",
        "expr": "isAllowed([{ effect: 'Allow', actions: ['s3:GetObject'], resources: ['photos/*'] }], 's3:GetObject', 'secrets/key.pem')",
        "expected": false
      },
      {
        "lang": "js",
        "expr": "isAllowed([{ effect: 'Allow', actions: ['s3:*'], resources: ['*'] }, { effect: 'Deny', actions: ['s3:DeleteObject'], resources: ['*'] }], 's3:DeleteObject', 'photos/cat.png')",
        "expected": false
      },
      {
        "lang": "js",
        "expr": "isAllowed([{ effect: 'Allow', actions: ['s3:*'], resources: ['*'] }, { effect: 'Deny', actions: ['s3:DeleteObject'], resources: ['*'] }], 's3:PutObject', 'photos/cat.png')",
        "expected": true
      }
    ]
  },
  {
    "id": "iac-check",
    "skillId": "iac",
    "type": "quiz",
    "title": "Terraform skill check",
    "description": "Pass this to master Terraform and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does terraform plan do?",
        "type": "multiple-choice",
        "options": [
          "Shows the changes it would make, without applying them",
          "Deletes infrastructure",
          "Formats files",
          "Writes provider code"
        ]
      },
      {
        "question": "For teams, Terraform state belongs in a shared backend with locking.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Apply planned changes with `terraform ___`.",
        "type": "fill-in-blank"
      }
    ]
  }
];
