// GENERATED by scripts/gen-catalog.ts from content/challenges.ts. Do not edit by hand.
// Contains no answers or explanations: those live only in Postgres (private.quiz_answers).
import type { Challenge } from "./types";

export const challenges: Challenge[] = [
  {
    "id": "html-check",
    "skillId": "html",
    "type": "quiz",
    "title": "HTML Skill Check",
    "description": "Pass this to master HTML and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does HTML stand for?",
        "type": "multiple-choice",
        "options": [
          "Home Tool Markup Language",
          "High Tech Modern Language",
          "Hyper Text Markup Language",
          "Hyperlinks and Text Markup Language"
        ],
        "hint": "Links between text (Hyper), the content (Text), and how it's structured (Markup)."
      },
      {
        "question": "Which tag is used for the largest heading?",
        "type": "multiple-choice",
        "options": [
          "<head>",
          "<heading>",
          "<h1>",
          "<h6>"
        ]
      },
      {
        "question": "HTML tags are case-sensitive.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "The _____ tag defines an unordered list.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "html-1",
    "skillId": "html",
    "type": "code",
    "lang": "html",
    "title": "Your First Page",
    "description": "Build a page with a title, a heading and a paragraph.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "<!DOCTYPE html>\n<html>\n  <!-- add a head with a title, and a body -->\n</html>\n",
    "hints": [
      "Put a <title> inside <head>",
      "Use <h1> for the heading and <p> for the paragraph",
      "Both go inside <body>"
    ],
    "tests": [
      {
        "lang": "html",
        "selector": "head > title",
        "label": "has a <title> in <head>"
      },
      {
        "lang": "html",
        "selector": "body h1",
        "label": "has an <h1> in <body>"
      },
      {
        "lang": "html",
        "selector": "body p",
        "label": "has a <p> in <body>"
      }
    ]
  },
  {
    "id": "css-check",
    "skillId": "css",
    "type": "quiz",
    "title": "CSS Skill Check",
    "description": "Pass this to master CSS and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which declaration makes an element a flex container?",
        "type": "multiple-choice",
        "options": [
          "flex: 1",
          "display: flex",
          "position: flex",
          "align: flex"
        ]
      },
      {
        "question": "Padding sits outside an element's border.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "The unit relative to the root element's font size is ___.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "css-1",
    "skillId": "css",
    "type": "code",
    "lang": "css",
    "title": "Center a Div",
    "description": "Center .container's children horizontally and vertically with flexbox.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": ".container {\n  /* your CSS here */\n}\n",
    "hints": [
      "Start with display: flex",
      "justify-content handles the main axis",
      "align-items handles the cross axis"
    ],
    "tests": [
      {
        "lang": "css",
        "selector": ".container",
        "prop": "display",
        "value": [
          "flex"
        ],
        "label": "display: flex"
      },
      {
        "lang": "css",
        "selector": ".container",
        "prop": "justify-content",
        "value": [
          "center"
        ],
        "label": "justify-content: center"
      },
      {
        "lang": "css",
        "selector": ".container",
        "prop": "align-items",
        "value": [
          "center"
        ],
        "label": "align-items: center"
      }
    ]
  },
  {
    "id": "css-2",
    "skillId": "css",
    "type": "code",
    "lang": "css",
    "title": "Three-Column Grid",
    "description": "Make .grid a grid with three equal columns and a gap.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": ".grid {\n  \n}\n",
    "hints": [
      "display: grid",
      "repeat(3, 1fr) makes three equal columns",
      "gap sets spacing between cells"
    ],
    "tests": [
      {
        "lang": "css",
        "selector": ".grid",
        "prop": "display",
        "value": [
          "grid"
        ],
        "label": "display: grid"
      },
      {
        "lang": "css",
        "selector": ".grid",
        "prop": "grid-template-columns",
        "value": [
          "repeat(3, 1fr)",
          "1fr 1fr 1fr"
        ],
        "label": "three equal columns"
      },
      {
        "lang": "css",
        "selector": ".grid",
        "prop": "gap",
        "value": [
          "*"
        ],
        "label": "has a gap"
      }
    ]
  },
  {
    "id": "javascript-check",
    "skillId": "javascript",
    "type": "quiz",
    "title": "JavaScript Skill Check",
    "description": "Pass this to master JavaScript and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does [1, 2, 3].map(x => x * 2) return?",
        "type": "multiple-choice",
        "options": [
          "[1, 2, 3]",
          "[2, 4, 6]",
          "6",
          "undefined"
        ]
      },
      {
        "question": "`const` makes an object immutable.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which operator compares value AND type?",
        "type": "multiple-choice",
        "options": [
          "!=",
          "===",
          "=",
          "=="
        ]
      }
    ]
  },
  {
    "id": "js-1",
    "skillId": "javascript",
    "type": "code",
    "lang": "js",
    "title": "Create a Function",
    "description": "Write add(a, b) that returns the sum of two numbers.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function add(a, b) {\n  // your code here\n}\n",
    "hints": [
      "Use the return keyword",
      "Return a + b"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "add(2, 3)",
        "expected": 5
      },
      {
        "lang": "js",
        "expr": "add(10, 20)",
        "expected": 30
      },
      {
        "lang": "js",
        "expr": "add(-1, 1)",
        "expected": 0
      }
    ]
  },
  {
    "id": "js-2",
    "skillId": "javascript",
    "type": "code",
    "lang": "js",
    "title": "Reverse a String",
    "description": "Write reverse(str) that returns the string backwards.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function reverse(str) {\n  \n}\n",
    "hints": [
      "Strings can be split into arrays",
      "Arrays have a reverse() method",
      "join('') turns an array back into a string"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "reverse('abc')",
        "expected": "cba"
      },
      {
        "lang": "js",
        "expr": "reverse('')",
        "expected": ""
      },
      {
        "lang": "js",
        "expr": "reverse('racecar')",
        "expected": "racecar"
      }
    ]
  },
  {
    "id": "js-3",
    "skillId": "javascript",
    "type": "code",
    "lang": "js",
    "title": "FizzBuzz",
    "description": "Write fizzBuzz(n) returning an array for 1..n: 'Fizz' for multiples of 3, 'Buzz' for 5, 'FizzBuzz' for both, otherwise the number.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "function fizzBuzz(n) {\n  const out = [];\n  \n  return out;\n}\n",
    "hints": [
      "Loop from 1 to n inclusive",
      "Check the 'both' case (i % 15) first",
      "Push numbers as numbers, not strings"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "fizzBuzz(5)",
        "expected": [
          1,
          2,
          "Fizz",
          4,
          "Buzz"
        ]
      },
      {
        "lang": "js",
        "expr": "fizzBuzz(15)[14]",
        "expected": "FizzBuzz"
      },
      {
        "lang": "js",
        "expr": "fizzBuzz(0)",
        "expected": []
      }
    ]
  },
  {
    "id": "js-game-1",
    "skillId": "javascript",
    "type": "game",
    "gameType": "debugger",
    "title": "Planet Debugger",
    "description": "Fix broken snippets against the clock to repair planets.",
    "difficulty": "intermediate",
    "xpReward": 100
  },
  {
    "id": "a11y-check",
    "skillId": "a11y",
    "type": "quiz",
    "title": "Accessibility Skill Check",
    "description": "Pass this to master Accessibility and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What should a purely decorative image's alt text be?",
        "type": "multiple-choice",
        "options": [
          "An empty string (alt=\"\")",
          "The file name",
          "\"image\"",
          "Leave out the alt attribute"
        ]
      },
      {
        "question": "A <div> with an onClick handler is as accessible as a <button>.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Minimum WCAG AA contrast for normal body text?",
        "type": "multiple-choice",
        "options": [
          "2:1",
          "4.5:1",
          "3:1",
          "7:1"
        ]
      }
    ]
  },
  {
    "id": "a11y-1",
    "skillId": "a11y",
    "type": "code",
    "lang": "html",
    "title": "Accessible Sign-up Form",
    "description": "Build a form where every input has a label, the image has alt text, and there's a real submit button.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "<form>\n  <img src=\"logo.png\">\n  <input type=\"email\">\n  <div onclick=\"submit()\">Sign up</div>\n</form>\n",
    "hints": [
      "Give the input an id and add <label for=\"that-id\">",
      "Every <img> needs an alt attribute",
      "Replace the div with <button type=\"submit\">"
    ],
    "tests": [
      {
        "lang": "html",
        "selector": "img[alt]",
        "label": "image has alt text"
      },
      {
        "lang": "html",
        "selector": "input[id]",
        "label": "input has an id"
      },
      {
        "lang": "html",
        "selector": "label[for]",
        "label": "a <label for=…> exists"
      },
      {
        "lang": "html",
        "selector": "button[type=\"submit\"]",
        "label": "uses <button type=\"submit\">"
      }
    ]
  },
  {
    "id": "tailwind-check",
    "skillId": "tailwind",
    "type": "quiz",
    "title": "Tailwind Skill Check",
    "description": "Pass this to master Tailwind and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which class applies only from the md breakpoint up?",
        "type": "multiple-choice",
        "options": [
          "md:flex",
          "flex:md",
          "@md flex",
          "flex-md"
        ]
      },
      {
        "question": "Tailwind ships every utility class to production whether you use it or not.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "The utility for display: grid is ___.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "typescript-check",
    "skillId": "typescript",
    "type": "quiz",
    "title": "TypeScript Skill Check",
    "description": "Pass this to master TypeScript and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What is the inferred type of x in let x = [1, 'a']?",
        "type": "multiple-choice",
        "options": [
          "unknown",
          "[number, string]",
          "any[]",
          "(string | number)[]"
        ]
      },
      {
        "question": "TypeScript types exist at runtime.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which check narrows value: string | number to string?",
        "type": "multiple-choice",
        "options": [
          "value!",
          "value instanceof String",
          "typeof value === 'string'",
          "value as string"
        ]
      }
    ]
  },
  {
    "id": "react-check",
    "skillId": "react",
    "type": "quiz",
    "title": "React Skill Check",
    "description": "Pass this to master React and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which hook runs side effects after render?",
        "type": "multiple-choice",
        "options": [
          "useState",
          "useMemo",
          "useRef",
          "useEffect"
        ]
      },
      {
        "question": "To add an item, call items.push(x) and then setItems(items).",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Items rendered with .map() need a unique ___ prop.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "nextjs-check",
    "skillId": "nextjs",
    "type": "quiz",
    "title": "Next.js Skill Check",
    "description": "Pass this to master Next.js and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "In the App Router, which file defines a route's UI?",
        "type": "multiple-choice",
        "options": [
          "index.tsx",
          "page.tsx",
          "route.tsx",
          "view.tsx"
        ]
      },
      {
        "question": "App Router components are Server Components by default.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which directive marks a client component?",
        "type": "multiple-choice",
        "options": [
          "\"use browser\"",
          "\"client only\"",
          "export const client = true",
          "\"use client\""
        ]
      }
    ]
  },
  {
    "id": "nodejs-check",
    "skillId": "nodejs",
    "type": "quiz",
    "title": "Node.js Skill Check",
    "description": "Pass this to master Node.js and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which file lists a Node project's dependencies?",
        "type": "multiple-choice",
        "options": [
          "node.config.js",
          "npmfile",
          "deps.txt",
          "package.json"
        ]
      },
      {
        "question": "Node runs your JavaScript on many threads by default.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "You can only use await inside a function marked ___ (or at the top level of an ES module).",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "nodejs-1",
    "skillId": "nodejs",
    "type": "code",
    "lang": "js",
    "title": "Parse a Query String",
    "description": "Write parseQuery(qs) turning 'a=1&b=two' into { a: '1', b: 'two' }. Decode percent-escapes like %20, and return {} for an empty string.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function parseQuery(qs) {\n  \n}\n",
    "hints": [
      "URLSearchParams is built in",
      "Object.fromEntries turns entries into an object"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "parseQuery('a=1&b=two')",
        "expected": {
          "a": "1",
          "b": "two"
        }
      },
      {
        "lang": "js",
        "expr": "parseQuery('')",
        "expected": {}
      },
      {
        "lang": "js",
        "expr": "parseQuery('q=hello%20world')",
        "expected": {
          "q": "hello world"
        }
      }
    ]
  },
  {
    "id": "express-check",
    "skillId": "express",
    "type": "quiz",
    "title": "Express Skill Check",
    "description": "Pass this to master Express and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does calling next() in middleware do?",
        "type": "multiple-choice",
        "options": [
          "Restarts the server",
          "Ends the response",
          "Skips every remaining route",
          "Passes control to the next middleware"
        ]
      },
      {
        "question": "Express error-handling middleware takes four arguments: (err, req, res, next).",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "With route '/users/:id', how do you read 42 from GET /users/42?",
        "type": "multiple-choice",
        "options": [
          "req.body.id",
          "req.query.id",
          "req.id",
          "req.params.id"
        ]
      }
    ]
  },
  {
    "id": "express-1",
    "skillId": "express",
    "type": "code",
    "lang": "js",
    "title": "Route Matcher",
    "description": "Write matchRoute(pattern, path): return an object of params if it matches, otherwise null. matchRoute('/users/:id', '/users/42') → { id: '42' }.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "function matchRoute(pattern, path) {\n  \n}\n",
    "hints": [
      "Split both on '/'",
      "Different segment counts means no match",
      "Segments starting with ':' capture a param"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "matchRoute('/users/:id', '/users/42')",
        "expected": {
          "id": "42"
        }
      },
      {
        "lang": "js",
        "expr": "matchRoute('/users/:id/posts/:postId', '/users/7/posts/9')",
        "expected": {
          "id": "7",
          "postId": "9"
        }
      },
      {
        "lang": "js",
        "expr": "matchRoute('/users/:id', '/teams/42')",
        "expected": null
      },
      {
        "lang": "js",
        "expr": "matchRoute('/users/:id', '/users/42/extra')",
        "expected": null
      }
    ]
  },
  {
    "id": "rest-apis-check",
    "skillId": "rest-apis",
    "type": "quiz",
    "title": "REST APIs Skill Check",
    "description": "Pass this to master REST APIs and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Status code for a newly created resource?",
        "type": "multiple-choice",
        "options": [
          "200 OK",
          "302 Found",
          "201 Created",
          "204 No Content"
        ]
      },
      {
        "question": "GET requests should never change server state.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which verb replaces a resource entirely?",
        "type": "multiple-choice",
        "options": [
          "GET",
          "PATCH",
          "POST",
          "PUT"
        ]
      }
    ]
  },
  {
    "id": "sql-check",
    "skillId": "sql",
    "type": "quiz",
    "title": "SQL Skill Check",
    "description": "Pass this to master SQL and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which clause filters groups after aggregation?",
        "type": "multiple-choice",
        "options": [
          "WHERE",
          "HAVING",
          "ORDER BY",
          "GROUP BY"
        ]
      },
      {
        "question": "An INNER JOIN keeps rows that have no match in the other table.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Remove duplicate rows with SELECT ___ …",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "postgres-check",
    "skillId": "postgres",
    "type": "quiz",
    "title": "PostgreSQL Skill Check",
    "description": "Pass this to master PostgreSQL and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which type stores JSON in a binary, indexable form?",
        "type": "multiple-choice",
        "options": [
          "hstore",
          "text",
          "json",
          "jsonb"
        ]
      },
      {
        "question": "A transaction applies all of its statements or none of them.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "What does Row Level Security control?",
        "type": "multiple-choice",
        "options": [
          "Which rows each user can read or write",
          "Which columns are indexed",
          "Disk encryption",
          "Replication lag"
        ]
      }
    ]
  },
  {
    "id": "auth-check",
    "skillId": "auth",
    "type": "quiz",
    "title": "Auth Skill Check",
    "description": "Pass this to master Auth and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "How should passwords be stored?",
        "type": "multiple-choice",
        "options": [
          "Hashed with a slow algorithm like bcrypt or argon2",
          "Encrypted with AES",
          "Plain text, since HTTPS protects them",
          "Base64-encoded"
        ]
      },
      {
        "question": "Anyone holding a (non-encrypted) JWT can read its payload.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "OAuth 2.0 is mainly a protocol for…",
        "type": "multiple-choice",
        "options": [
          "Encrypting databases",
          "Load balancing",
          "Password hashing",
          "Delegated authorization"
        ]
      }
    ]
  },
  {
    "id": "auth-1",
    "skillId": "auth",
    "type": "code",
    "lang": "js",
    "title": "Token Expiry",
    "description": "Write isExpired(payload, nowMs). JWT `exp` is in seconds; nowMs is milliseconds. Expired when now ≥ exp.",
    "difficulty": "beginner",
    "xpReward": 50,
    "starterCode": "function isExpired(payload, nowMs) {\n  \n}\n",
    "hints": [
      "Convert exp to milliseconds (× 1000)",
      "Use >= so a token is expired exactly at exp"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "isExpired({ exp: 100 }, 100000)",
        "expected": true
      },
      {
        "lang": "js",
        "expr": "isExpired({ exp: 200 }, 100000)",
        "expected": false
      },
      {
        "lang": "js",
        "expr": "isExpired({ exp: 100 }, 99999)",
        "expected": false
      }
    ]
  },
  {
    "id": "fastapi-check",
    "skillId": "fastapi",
    "type": "quiz",
    "title": "FastAPI Skill Check",
    "description": "Pass this to master FastAPI and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does FastAPI use to validate request bodies?",
        "type": "multiple-choice",
        "options": [
          "Pydantic models",
          "SQLAlchemy",
          "Regular expressions",
          "Hand-written if statements"
        ]
      },
      {
        "question": "FastAPI serves interactive OpenAPI docs at /docs automatically.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Declare an async endpoint with `___ def read_item(...)`.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "python-check",
    "skillId": "python",
    "type": "quiz",
    "title": "Python Skill Check",
    "description": "Pass this to master Python and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What is len([1, [2, 3], 4])?",
        "type": "multiple-choice",
        "options": [
          "Error",
          "4",
          "3",
          "2"
        ]
      },
      {
        "question": "Python lists are immutable.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Which of these creates a dict?",
        "type": "multiple-choice",
        "options": [
          "{'a', 1}",
          "['a', 1]",
          "{'a': 1}",
          "('a', 1)"
        ]
      }
    ]
  },
  {
    "id": "pandas-check",
    "skillId": "pandas",
    "type": "quiz",
    "title": "pandas Skill Check",
    "description": "Pass this to master pandas and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Select rows where the age column is over 30:",
        "type": "multiple-choice",
        "options": [
          "df.where(age > 30)",
          "df.select('age > 30')",
          "df[df['age'] > 30]",
          "df.filter(age > 30)"
        ]
      },
      {
        "question": "df.dropna() modifies df in place by default.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Mean salary per department?",
        "type": "multiple-choice",
        "options": [
          "df.mean('dept')",
          "df.groupby('dept')['salary'].mean()",
          "df.pivot('salary')",
          "df.agg('dept')"
        ]
      }
    ]
  },
  {
    "id": "pandas-1",
    "skillId": "pandas",
    "type": "code",
    "lang": "js",
    "title": "Group By, by Hand",
    "description": "Write groupMean(rows, key, field) returning { [group]: mean } — what df.groupby(key)[field].mean() does.",
    "difficulty": "intermediate",
    "xpReward": 60,
    "starterCode": "function groupMean(rows, key, field) {\n  \n}\n",
    "hints": [
      "Accumulate a sum and count per group",
      "Then divide sum by count for each group"
    ],
    "tests": [
      {
        "lang": "js",
        "expr": "groupMean([{d:'a',s:10},{d:'a',s:20},{d:'b',s:5}], 'd', 's')",
        "expected": {
          "a": 15,
          "b": 5
        }
      },
      {
        "lang": "js",
        "expr": "groupMean([], 'd', 's')",
        "expected": {}
      }
    ]
  },
  {
    "id": "data-viz-check",
    "skillId": "data-viz",
    "type": "quiz",
    "title": "Data Viz Skill Check",
    "description": "Pass this to master Data Viz and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Best chart for a trend over time?",
        "type": "multiple-choice",
        "options": [
          "Treemap",
          "Scatter plot",
          "Line chart",
          "Pie chart"
        ]
      },
      {
        "question": "Bar charts should start their value axis at zero.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Comparing 12 categories' share of a whole is clearest as…",
        "type": "multiple-choice",
        "options": [
          "A line chart",
          "A sorted bar chart",
          "A 3D pie chart",
          "A 12-slice pie chart"
        ]
      }
    ]
  },
  {
    "id": "ml-basics-check",
    "skillId": "ml-basics",
    "type": "quiz",
    "title": "ML Basics Skill Check",
    "description": "Pass this to master ML Basics and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "99% accuracy on training data, 60% on test data. This is…",
        "type": "multiple-choice",
        "options": [
          "Good generalisation",
          "Overfitting",
          "Regularization",
          "Underfitting"
        ]
      },
      {
        "question": "It's fine to evaluate a model on the data it was trained on.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Predicting a house price is…",
        "type": "multiple-choice",
        "options": [
          "Clustering",
          "Classification",
          "Reinforcement learning",
          "Regression"
        ]
      }
    ]
  },
  {
    "id": "deep-learning-check",
    "skillId": "deep-learning",
    "type": "quiz",
    "title": "Deep Learning Skill Check",
    "description": "Pass this to master Deep Learning and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does gradient descent minimize?",
        "type": "multiple-choice",
        "options": [
          "The dataset size",
          "The loss function",
          "The learning rate",
          "The number of layers"
        ]
      },
      {
        "question": "Transformers rely on attention rather than recurrence.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Dense vector representations of words or items are called ___.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "llm-apps-check",
    "skillId": "llm-apps",
    "type": "quiz",
    "title": "LLM Apps Skill Check",
    "description": "Pass this to master LLM Apps and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "RAG stands for…",
        "type": "multiple-choice",
        "options": [
          "Recursive Answer Graph",
          "Rapid API Gateway",
          "Random Attention Gradient",
          "Retrieval-Augmented Generation"
        ]
      },
      {
        "question": "Lowering temperature makes output more deterministic.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Best way to know if a prompt change made your app better?",
        "type": "multiple-choice",
        "options": [
          "Ask the model if it improved",
          "Run it against an eval set",
          "Make the prompt longer",
          "Try one example by hand"
        ]
      }
    ]
  },
  {
    "id": "git-check",
    "skillId": "git",
    "type": "quiz",
    "title": "Git Skill Check",
    "description": "Pass this to master Git and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Which command creates and switches to a new branch?",
        "type": "multiple-choice",
        "options": [
          "git commit -b feature",
          "git switch -c feature",
          "git branch --go feature",
          "git new feature"
        ]
      },
      {
        "question": "git pull is git fetch followed by a merge (or rebase).",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Stage everything in the current directory with `git ___ .`",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "linux-check",
    "skillId": "linux",
    "type": "quiz",
    "title": "Linux Skill Check",
    "description": "Pass this to master Linux and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does chmod 755 give the file's owner?",
        "type": "multiple-choice",
        "options": [
          "Read, write and execute",
          "Nothing",
          "Execute only",
          "Read only"
        ]
      },
      {
        "question": "In `ls | grep log`, ls's output becomes grep's input.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Print the current working directory with ___.",
        "type": "fill-in-blank"
      }
    ]
  },
  {
    "id": "docker-check",
    "skillId": "docker",
    "type": "quiz",
    "title": "Docker Skill Check",
    "description": "Pass this to master Docker and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "An image is to a container as…",
        "type": "multiple-choice",
        "options": [
          "A branch is to a commit",
          "A port is to a host",
          "A VM is to a disk",
          "A class is to an instance"
        ]
      },
      {
        "question": "Files written inside a container survive `docker rm` by default.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Why use multi-stage builds?",
        "type": "multiple-choice",
        "options": [
          "Smaller final images without build tools",
          "To run several OSes",
          "Faster network",
          "To avoid writing a Dockerfile"
        ]
      }
    ]
  },
  {
    "id": "ci-cd-check",
    "skillId": "ci-cd",
    "type": "quiz",
    "title": "CI/CD Skill Check",
    "description": "Pass this to master CI/CD and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "Where do GitHub Actions workflows live?",
        "type": "multiple-choice",
        "options": [
          "actions/",
          ".github/workflows/",
          ".git/hooks/",
          ".ci/"
        ]
      },
      {
        "question": "CI means merging small changes often, verified by automated tests.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "A deploy breaks production. Usually the fastest safe move is…",
        "type": "multiple-choice",
        "options": [
          "Debug live in production",
          "Roll back to the last good release",
          "Turn off monitoring",
          "Delete the logs"
        ]
      }
    ]
  },
  {
    "id": "kubernetes-check",
    "skillId": "kubernetes",
    "type": "quiz",
    "title": "Kubernetes Skill Check",
    "description": "Pass this to master Kubernetes and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "The smallest deployable unit in Kubernetes is a…",
        "type": "multiple-choice",
        "options": [
          "Namespace",
          "Node",
          "Container image",
          "Pod"
        ]
      },
      {
        "question": "A Deployment keeps the desired number of replicas running.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "What gives a set of pods a stable network address?",
        "type": "multiple-choice",
        "options": [
          "A Secret",
          "A Service",
          "A ConfigMap",
          "A Volume"
        ]
      }
    ]
  },
  {
    "id": "cloud-check",
    "skillId": "cloud",
    "type": "quiz",
    "title": "Cloud Skill Check",
    "description": "Pass this to master Cloud and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "The rule for granting IAM permissions is…",
        "type": "multiple-choice",
        "options": [
          "Share the root credentials",
          "Least privilege",
          "Grant everything, revoke later",
          "Admin for everyone"
        ]
      },
      {
        "question": "Object storage like S3 is a good fit for user-uploaded images.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Autoscaling adds capacity based on…",
        "type": "multiple-choice",
        "options": [
          "Number of git commits",
          "The time zone",
          "Load metrics like CPU or request rate",
          "Team size"
        ]
      }
    ]
  },
  {
    "id": "iac-check",
    "skillId": "iac",
    "type": "quiz",
    "title": "Terraform Skill Check",
    "description": "Pass this to master Terraform and light up its star.",
    "difficulty": "beginner",
    "xpReward": 30,
    "questions": [
      {
        "question": "What does terraform plan do?",
        "type": "multiple-choice",
        "options": [
          "Shows the changes it would make, without applying them",
          "Deletes infrastructure",
          "Formats files",
          "Writes provider code"
        ]
      },
      {
        "question": "For teams, Terraform state belongs in a shared backend with locking.",
        "type": "true-false",
        "options": [
          "True",
          "False"
        ]
      },
      {
        "question": "Apply planned changes with `terraform ___`.",
        "type": "fill-in-blank"
      }
    ]
  }
];
