// Pure build step shared by gen-catalog (writes files), check-bundle and the tests.
// Splits the authoring source into
//   - a public catalog for the browser: questions and options, no answers;
//   - a private answer key + skill graph for Postgres (supabase/catalog.sql).
import { skills } from "../src/content/skills.ts";
import { challenges as authored, type AuthoredQuestion } from "../content/challenges.ts";
import type { Challenge, Question } from "../src/content/types.ts";

/** Must match private.normalize_answer in the grading migration. */
export const normalizeAnswer = (s: string) => s.replace(/[<>`]/g, "").trim().toLowerCase();

// Deterministic shuffle (FNV-1a seed + mulberry32) so generated files are stable in git.
const seedOf = (s: string) => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
};
const rng = (seed: number) => () => {
  seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

export interface AnswerRow {
  challengeId: string;
  idx: number;
  accepted: string[];
  explanation: string;
}

const publish = (challengeId: string, idx: number, q: AuthoredQuestion): { question: Question; answer: AnswerRow } => {
  const base = { challengeId, idx, explanation: q.explanation };
  if (q.type === "fill-in-blank") {
    const accepted = [...new Set([q.correctAnswer as string, ...(q.alsoAccept ?? [])].map(normalizeAnswer))];
    return { question: { question: q.question, type: q.type, hint: q.hint }, answer: { ...base, accepted } };
  }
  const order = q.options!.map((_, i) => i);
  if (q.type === "multiple-choice") {
    const next = rng(seedOf(`${challengeId}#${idx}`));
    for (let i = order.length - 1; i > 0; i--) {
      const j = Math.floor(next() * (i + 1));
      [order[i], order[j]] = [order[j], order[i]];
    }
  }
  return {
    question: { question: q.question, type: q.type, options: order.map((i) => q.options![i]), hint: q.hint },
    answer: { ...base, accepted: [String(order.indexOf(q.correctAnswer as number))] },
  };
};

export const buildCatalog = () => {
  const answers: AnswerRow[] = [];
  const publicChallenges: Challenge[] = authored.map((c) => {
    if (c.type !== "quiz") return c;
    const questions = c.questions.map((q, idx) => {
      const { question, answer } = publish(c.id, idx, q);
      answers.push(answer);
      return question;
    });
    return { ...c, questions };
  });
  return { skills, publicChallenges, answers };
};

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (xs: string[]) => `array[${xs.map(q).join(", ")}]::text[]`;

export const catalogSql = ({ skills, publicChallenges, answers } = buildCatalog()) => `-- GENERATED by scripts/gen-catalog.ts from content/ and src/content/skills.ts. Do not edit by hand.
begin;

insert into public.skills (id, track, requires) values
${skills.map((s) => `  (${q(s.id)}, ${q(s.track)}, ${arr(s.requires)})`).join(",\n")}
on conflict (id) do update set track = excluded.track, requires = excluded.requires;

insert into public.challenges (id, skill_id, xp, kind) values
${publicChallenges.map((c) => `  (${q(c.id)}, ${q(c.skillId)}, ${c.xpReward}, ${q(c.type)})`).join(",\n")}
on conflict (id) do update set skill_id = excluded.skill_id, xp = excluded.xp, kind = excluded.kind;

delete from public.challenges where id not in (${publicChallenges.map((c) => q(c.id)).join(", ")});
delete from public.skills where id not in (${skills.map((s) => q(s.id)).join(", ")});

-- Answer key: only reachable through check_answer() / submit_quiz().
delete from private.quiz_answers;
insert into private.quiz_answers (challenge_id, idx, accepted, explanation) values
${answers.map((a) => `  (${q(a.challengeId)}, ${a.idx}, ${arr(a.accepted)}, ${q(a.explanation)})`).join(",\n")};

commit;
`;

export const publicModule = ({ publicChallenges } = buildCatalog()) => `// GENERATED by scripts/gen-catalog.ts from content/challenges.ts. Do not edit by hand.
// Contains no answers or explanations: those live only in Postgres (private.quiz_answers).
import type { Challenge } from "./types";

export const challenges: Challenge[] = ${JSON.stringify(publicChallenges, null, 2)};
`;
