// Mirrors the skill graph + challenge XP from src/content into supabase/catalog.sql,
// so the database can validate completions. Run: npm run db:catalog
// CI fails if the committed file is stale.
import { writeFileSync } from "node:fs";
import { skills } from "../src/content/skills.ts";
import { challenges } from "../src/content/challenges.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (xs: string[]) => `array[${xs.map(q).join(", ")}]::text[]`;

const sql = `-- GENERATED by scripts/gen-catalog.ts from src/content. Do not edit by hand.
begin;

insert into public.skills (id, track, requires) values
${skills.map((s) => `  (${q(s.id)}, ${q(s.track)}, ${arr(s.requires)})`).join(",\n")}
on conflict (id) do update set track = excluded.track, requires = excluded.requires;

insert into public.challenges (id, skill_id, xp) values
${challenges.map((c) => `  (${q(c.id)}, ${q(c.skillId)}, ${c.xpReward})`).join(",\n")}
on conflict (id) do update set skill_id = excluded.skill_id, xp = excluded.xp;

delete from public.challenges where id not in (${challenges.map((c) => q(c.id)).join(", ")});
delete from public.skills where id not in (${skills.map((s) => q(s.id)).join(", ")});

commit;
`;

writeFileSync(new URL("../supabase/catalog.sql", import.meta.url), sql);
console.log(`catalog.sql: ${skills.length} skills, ${challenges.length} challenges`);
